### ISSUE TITLE
Plugin Myhero Mobs not working

### ISSUE THREAD

**Issue by chicuong2412** [EnterTG/MyHero_Items_Nukkit#5]
this is error:
Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: de/kniffo80/mobplugin/entities/animal/walking/Sheep
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [a.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [a.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) [a.jar:?]
        at cn.nukkit.Server.<init>(Server.java:558) [a.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [a.jar:?]
Caused by: java.lang.NoClassDefFoundError: de/kniffo80/mobplugin/entities/animal/walking/Sheep
        at MyHero_Core.DataManagment.DataMobs.Start(DataMobs.java:57) ~[?:?]
        at MyHero_Mobs.Core.MyHeroMain_Mobs.onEnable(MyHeroMain_Mobs.java:18) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[a.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[a.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[a.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: de.kniffo80.mobplugin.entities.animal.walking.Sheep
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[a.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[a.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at MyHero_Core.DataManagment.DataMobs.Start(DataMobs.java:57) ~[?:?]
        at MyHero_Mobs.Core.MyHeroMain_Mobs.onEnable(MyHeroMain_Mobs.java:18) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[a.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[a.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[a.jar:?]

**Comment by EnterTG** [comment]
MyHero Mobs 1.12 and HyHero Core 1.22 should fix your error
