### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by urhuckleberry51** [EnterTG/MyHero_Items_Nukkit#6]
![Screenshot_20190730-113906_Samsung Internet](https://user-images.githubusercontent.com/46268645/62143967-f8d8d100-b2be-11e9-828f-f1af0144e518.jpg)
![Screenshot_20190730-113917_Samsung Internet](https://user-images.githubusercontent.com/46268645/62143984-00987580-b2bf-11e9-9246-17f4245b6e84.jpg)

**Comment by EnterTG** [comment]
Give it in normal text. Which version of MyHeroLevels and MyHeroCore are you using?

**Comment by urhuckleberry51** [comment]
I got it off of the nukkit plugins site so newest

**Comment by EnterTG** [comment]
1. Give me this error in the text, not on the screen shot, which is difficult to read.
2. Give me a list of installed plugins

**Comment by Antirivoluzion** [comment]
Same error m

**Comment by EnterTG** [comment]
Antirivoluzion give error message, list of plugins and nukkit version.

**Comment by Antirivoluzion** [comment]
WorldBorder v1.2, KotlinLib v1.1, WalkingParticles v1.0, EconomyAPI v2.0.0, Targets v1.0.0, GTTrade v1.0, Portals v1.0, ZCombatLogger v1.0, SimpleScoreboards v2.2.1, BowHitAlert v1.0, AdvancedKits v2.3, PlaceholderAPI v1.3.1, ScoreboardPlugin v1.0, MaxEnchants v1.1-SNAPSHOT, InfoBook v1.1, AutoSpawn v1.0, Trading_Interface v1.0.2, MoreFeatures v1.0.1, VPNGuard v3.1, LoveTrolls v1, ItemJose v1.0, ZCommandBan v1.0, ScoreTag v1.0.1, MobEarn v1.0.0, Report v1.2, SimpleGenerator v0.5, ProtectedWorlds v1.0.2, AdvancedBan v3.0.1-SNAPSHOT, SVault v2.2, Snowball_Griefing v1.0.0, FastAsyncWorldEdit v19.01.12-dc2d277-1245-22.0.7, BuycraftX v12.0.2, TouchToDo v1.0.0, Pets v1.3, PlugMan v1.0, LuckyBlocks-Nukkit v1.0.0, LoveRTP v1, FireworkShow v1.0, NoCaps v1.0.1, BlodParticles v1.0.0, Advanced-Welcome v0.1, SimpleAnnouncer v0.5, AutoRestart v3.3.3, CustomJoinLeaveMessage v1.1, Pokkit v0.8.1, Fake v1.2, SimpleCrates v1.0, EssentialsNK v1.8.0, ObsidianBoom v1.0, MultiWorld v1.0, RollBossBar v1.2.0, PowerTools v1.1, EPearlCooldown v1.0, CustomDeathMessage v3.0.0, QuickSpawns v1.0, DbLib v0.2.5, Holograms v3.1.3, WeatherLock v1.0, XHud v2.0, LoveDiguise v1, DynamicMOTD v0.1, MobPlugin v1.10.4, Trading_Commands v1.0.4, BouncyBlocks v1.0, AntiSpam v1.0.0, NPC v2.2.4, Presents v1.6, NoSpaceInName v1.0, PocketMine-MP v1.0.0, Maps v1.0, FakeInventories v1.0.2, CooldownAPI v1.0, Factions v1.7.0, Gsound v5.0, LoggerX v1.0.1, PocketVote v2.0.1-bDEV, Multipass v1.1.2, SilkSpawnner v1.0, SRegionProtector v20.1, EssentialsNK-Form v1.0, MyHero v1.22, MyHeroLevels v1.01, MultiChat vCUSTOM_FACTIONS, SeeInv v1.0, MyHeroMobs v1.12




Last nukkit


Error: Throwing
java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.Server.<init>(Server.java:483) [nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT%20(10).jar:?]
Caused by: java.lang.NullPointerException
        at MyHero_Core.Managers.ConnectionManager.InitConnection(ConnectionManager.java:21) ~[?:?]
        at MyHero_Core.Core.Data.InitData(Data.java:39) ~[?:?]
        at MyHero_Core.Core.MyHeroMain.onEnable(MyHeroMain.java:23) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT%20(10).jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit-1.0-SNAPSHOT%20(10).jar:?]
        ... 4 more



Same thing for myherolevels

**Comment by EnterTG** [comment]
This is a config error, check if do you have this, in your config
Default:
 UseMySql: false
 MySqlIP: 0.0.0.0
 MySqlLogin: root
 MySqlPass: ""
 MySqlDatabase: "main"
 MySqlPort: 0

and this 

Levels:
 MaxLevel: 40
 Equation: "%level%*2+3^(%level%+2)"
